spring:
  data:
    mongodb:
      host: 'localhost:27017'
      database: martianrobots
      username: guidesmiths
      password: martianrobots
      authentication-database: admin

logging:
  level:
    root: info

size.max: 10