spring:
  data:
    mongodb:
      host: '${MONGO_HOST:martianrobotsdb}:27017'
      database: '${MONGO_DB:martianrobots}'
      username: '${MONGO_USER:guidesmiths}'
      password: '${MONGO_PASS:martianrobots}'
      authentication-database: '${MONGO_DB:admin}'

logging:
  level:
    root: info

size.max: 10